name: trigger

on:
  workflow_dispatch:
  schedule:
    - cron:  '02 14 * * *'


jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ./workflow-trigger.sh
